spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hessbnb?currentSchema=schema_users
    username: hessbnb
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: schema_users
    open-in-view: false
  flyway:
    enabled: true
    schemas: schema_users
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/hessbnb
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://postgres:5432/hessbnb?currentSchema=schema_users
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/hessbnb/protocol/openid-connect/certs
  rabbitmq:
    host: rabbitmq
