spring:
  application:
    name: rental-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hessbnb?currentSchema=schema_rentals
    username: hessbnb
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: schema_rentals
    open-in-view: false
  flyway:
    enabled: true
    schemas: schema_rentals
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/hessbnb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/hessbnb?currentSchema=schema_rentals
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/hessbnb/protocol/openid-connect/certs
  rabbitmq:
    host: rabbitmq
