spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

services:
  message-url: http://localhost:8085

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq
services:
  message-url: http://message-service:8085
